name: build
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags: ["v[0-9]+*"]

jobs:
  tests:
    name: Tests (jvm \${{ matrix.java }})
    strategy:
      fail-fast: true      
      matrix:
        os: [ubuntu-20.04]
        java: [11]
        command: ["ci"]

    runs-on: \${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.\${{ matrix.java }}"

      - name: sbt \${{ matrix.command }}
        run: |
          sbt -J-Xmx6144m \${{ matrix.command }}
        env:
          SCALA_VERSION: \${{ matrix.scala }}
          SBT_COMMAND: \${{ matrix.command }}
